name: Deploy Site

on:
  push:
    branches: [main]

jobs:
  deploy-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run:  make
      - uses: actions/setup-node@v3
        with:
          node-version: 20.5.1
      - name: Build site
        run: make build-site

      - name: Deploy site
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: gh-page
          folder: docs
          single-commit: true
          clean: true